[package]
name = "client"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2024"
publish = false
license = "Apache-2.0 OR Zlib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
server = { path = "../server" }
tracing = "0.1.10"
ash = { version = "0.38.0", default-features = false, features = ["loaded", "debug", "std"] }
lahar = { git = "https://github.com/Ralith/lahar", rev = "67c190a000472720f7e9dc93899bcaaa72fe1574" }
yakui = "0.3.0"
yakui-vulkan = "0.3.0"
winit = "0.30.4"
ash-window = "0.13"
raw-window-handle = "0.6"
directories = "6.0.0"
vk-shader-macros = "0.2.5"
nalgebra = { workspace = true }
libm = "0.2.16"
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "sync", "macros"] }
tokio-util = "0.7.19"
pollster = "1.0.1"
png = "0.18.0"
anyhow = "1.0.26"
serde = { version = "1.0.104", features = ["derive", "rc"] }
toml = { workspace = true }
fxhash = "0.2.1"
downcast-rs = "2.0.0"
quinn = { workspace = true }
futures-util = "0.3.1"
webpki = "0.22.4"
hecs = { workspace = true }
memoffset = "0.9"
gltf = { version = "1.0.0", default-features = false, features = ["utils"] }
metrics = "0.24.0"
hdrhistogram = { version = "7", default-features = false }
save = { path = "../save" }
lru-slab = "0.1.2"
skid-steer = { git="https://github.com/Ralith/skid-steer", rev = "16feada2408810f78a9f469001ef9277e98d4061" }
color = "0.3.3"

[features]
default = ["use-repo-assets"]
use-repo-assets = []

[dev-dependencies]
approx = "0.5.1"
bencher = "0.1.5"
renderdoc = "0.12.1"

[[bench]]
name = "surface_extraction"
harness = false
