version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  # Ignore raw-window-handle because it's tied to ash-window
  - dependency-name: raw-window-handle
  # Ignore rustls and rustls-pemfile because they're tied to quinn
  - dependency-name: rustls
  - dependency-name: rustls-pemfile
