version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: whoami
    versions:
    - 1.1.0
    - 1.1.1
  - dependency-name: rustls
    versions:
    - 0.19.0
  - dependency-name: directories
    versions:
    - 3.0.1
